#!/usr/bin/env node
/**
 * Data import pipeline: reads a raw research JSON file (real, sourced records - see
 * README in this folder), normalizes + dedupes it against the existing curated data, and
 * injects the survivors into the region's waterbodies.ts file as an auto-generated,
 * clearly-marked block. Safe to re-run: regenerating replaces the previous generated
 * block without touching the hand-curated entries above it.
 *
 * Usage: node scripts/data-pipeline/generate.mjs <washington|florida> [--input path.json]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { normalizeImportRecord } from "./normalize.mjs";
import { dedupeRecords } from "./dedupe.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");

const REGION_CONFIG = {
  washington: {
    file: join(root, "src/data/waterbodies/washington.ts"),
    helper: "wa",
    arrayName: "washingtonWaterbodies",
    defaultInput: "/private/tmp/claude-501/-Users-abdallahelhamawi/6d09dfec-8931-42d9-b0b4-9acfe3fc2e71/scratchpad/wa-waterbodies-import.json"
  },
  florida: {
    file: join(root, "src/data/waterbodies/florida.ts"),
    helper: "fl",
    arrayName: "floridaWaterbodies",
    defaultInput: "/private/tmp/claude-501/-Users-abdallahelhamawi/6d09dfec-8931-42d9-b0b4-9acfe3fc2e71/scratchpad/fl-waterbodies-import.json"
  }
};

const BEGIN = "  // BEGIN PIPELINE IMPORT (auto-generated by scripts/data-pipeline/generate.mjs - do not hand-edit this block, rerun the script instead)";
const END = "  // END PIPELINE IMPORT";

function extractExistingIdsAndNames(source, helper) {
  const callRegex = new RegExp(`${helper}\\(\\s*"([^"]+)"\\s*,\\s*"([^"]+)"`, "g");
  const ids = new Set();
  const names = [];
  let match;
  while ((match = callRegex.exec(source))) {
    ids.add(match[1]);
    names.push(match[2]);
  }
  return { ids, names };
}

function uniqueId(baseId, takenIds) {
  if (!takenIds.has(baseId)) return baseId;
  let suffix = 2;
  while (takenIds.has(`${baseId}-${suffix}`)) suffix += 1;
  return `${baseId}-${suffix}`;
}

function jsStringArray(items) {
  return `[${items.map((item) => JSON.stringify(item)).join(", ")}]`;
}

function generateCallLine(helper, record) {
  const area = record.city || record.county || record.name;
  const status = "restricted";
  const shoreAccessDifficulty = "Moderate";
  const beginnerDifficulty = "Moderate";
  const parkingNote = "Parking and access details not yet field-verified for this location.";
  const regulationSummary = "Imported from public source data; verify current season, limits, and access rules before fishing.";
  const suggestedBait = ["Verify locally"];
  const recommendedRigs = ["Verify locally"];
  const bestSeason = "Verify current season and regulations.";
  const todayRecommendation = "Verify official rules and current conditions before you go - this location was imported from public source data and hasn't been field-verified yet.";

  const provenanceParts = [
    `sourceUrl: ${JSON.stringify(record.sourceUrl)}`,
    record.sourceOrganization ? `sourceOrganization: ${JSON.stringify(record.sourceOrganization)}` : null,
    `verificationStatus: ${JSON.stringify(record.verificationStatus)}`,
    record.accessType ? `accessType: ${JSON.stringify(record.accessType)}` : null,
    `activities: ${jsStringArray(record.activities)}`
  ].filter(Boolean).join(", ");

  const args = [
    JSON.stringify(record.id),
    JSON.stringify(record.name),
    JSON.stringify(area),
    JSON.stringify(record.county ?? ""),
    JSON.stringify(record.waterType),
    record.latitude,
    record.longitude,
    "[]",
    JSON.stringify(status),
    JSON.stringify(shoreAccessDifficulty),
    JSON.stringify(beginnerDifficulty),
    JSON.stringify(parkingNote),
    JSON.stringify(regulationSummary),
    jsStringArray(suggestedBait),
    jsStringArray(recommendedRigs),
    JSON.stringify(bestSeason),
    JSON.stringify(todayRecommendation),
    `{ ${provenanceParts} }`
  ];

  return `  ${helper}(${args.join(", ")})`;
}

function stripExistingBlock(source) {
  const beginIdx = source.indexOf(BEGIN);
  if (beginIdx === -1) return source;
  const endIdx = source.indexOf(END, beginIdx);
  if (endIdx === -1) return source;
  const afterEndLineStart = source.indexOf("\n", endIdx) + 1;
  return source.slice(0, beginIdx) + source.slice(afterEndLineStart);
}

function insertBlock(source, generatedLines) {
  const cleaned = stripExistingBlock(source);
  const closeMarker = "\n];\n";
  const idx = cleaned.lastIndexOf(closeMarker);
  if (idx === -1) throw new Error("Could not find the array's closing `];` in the target file.");

  let before = cleaned.slice(0, idx);
  const after = cleaned.slice(idx + 1); // keep leading "];\n"
  before = before.replace(/[ \t\n]+$/, "");
  const needsComma = before.length > 0 && !before.endsWith(",");
  before += needsComma ? ",\n" : "\n";

  const block = generatedLines.length > 0 ? `${BEGIN}\n${generatedLines.join(",\n")}\n${END}\n` : "";
  return before + block + after;
}

function main() {
  const [regionArg, ...rest] = process.argv.slice(2);
  const config = REGION_CONFIG[regionArg];
  if (!config) {
    console.error(`Usage: node scripts/data-pipeline/generate.mjs <${Object.keys(REGION_CONFIG).join("|")}> [--input path.json]`);
    process.exit(1);
  }

  const inputFlagIndex = rest.indexOf("--input");
  const inputPath = inputFlagIndex !== -1 ? rest[inputFlagIndex + 1] : config.defaultInput;

  const raw = JSON.parse(readFileSync(inputPath, "utf8"));
  if (!Array.isArray(raw)) {
    console.error("Input file must be a JSON array of records.");
    process.exit(1);
  }

  const source = readFileSync(config.file, "utf8");
  // Compute "existing" against the hand-curated content only - otherwise a second run would
  // see the first run's own generated block as "existing" and dedupe everything away.
  const curatedOnlySource = stripExistingBlock(source);
  const { ids: existingIds, names: existingNames } = extractExistingIdsAndNames(curatedOnlySource, config.helper);

  const normalized = [];
  const rejected = [];
  for (const item of raw) {
    const result = normalizeImportRecord(item, regionArg);
    if (result.error) rejected.push(result.error);
    else normalized.push(result.record);
  }

  const { kept, droppedAgainstExisting, droppedInternal } = dedupeRecords(normalized, existingNames);

  const takenIds = new Set(existingIds);
  for (const record of kept) {
    record.id = uniqueId(record.id, takenIds);
    takenIds.add(record.id);
  }

  const generatedLines = kept.map((record) => generateCallLine(config.helper, record));
  const nextSource = insertBlock(source, generatedLines);
  writeFileSync(config.file, nextSource, "utf8");

  const sourceOrgCounts = {};
  for (const record of kept) {
    const key = record.sourceOrganization || "unknown";
    sourceOrgCounts[key] = (sourceOrgCounts[key] ?? 0) + 1;
  }
  const verificationCounts = {};
  for (const record of kept) {
    verificationCounts[record.verificationStatus] = (verificationCounts[record.verificationStatus] ?? 0) + 1;
  }

  console.log(`\n${regionArg} import summary`);
  console.log(`  input records:              ${raw.length}`);
  console.log(`  rejected (invalid):         ${rejected.length}`);
  console.log(`  dropped (dup of existing):  ${droppedAgainstExisting.length}`);
  console.log(`  dropped (dup within batch): ${droppedInternal.length}`);
  console.log(`  written:                    ${kept.length}`);
  console.log(`  by source org:              ${JSON.stringify(sourceOrgCounts)}`);
  console.log(`  by verification status:     ${JSON.stringify(verificationCounts)}`);
  if (rejected.length) {
    console.log(`\n  rejected reasons (first 20):`);
    rejected.slice(0, 20).forEach((reason) => console.log(`    - ${reason}`));
  }
}

main();
